# The prototypeApp framework was is taken from
# https://github.com/saullocastro/programming/archive/master.zip
# by Saullo G P Castro of TU Delft.
"""
This module defines icons used for the prototype application.
"""

dialogIconData = [
"24 24 2 1",
"  c navy",
"X c None s None",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXX            XXXXXXXXX",
"XXX              XXXXXXX",
"XXX               XXXXXX",
"XXX    XXXXXX      XXXXX",
"XXX    XXXXXXX      XXXX",
"XXX    XXXXXXXX     XXXX",
"XXX    XXXXXXXX     XXXX",
"XXX    XXXXXXXXX     XXX",
"XXX    XXXXXXXXX     XXX",
"XXX    XXXXXXXXX     XXX",
"XXX    XXXXXXXXX     XXX",
"XXX    XXXXXXXXX     XXX",
"XXX    XXXXXXXXX     XXX",
"XXX    XXXXXXXX     XXXX",
"XXX    XXXXXXXX     XXXX",
"XXX    XXXXXXX      XXXX",
"XXX    XXXXXXX     XXXXX",
"XXX               XXXXXX",
"XXX              XXXXXXX",
"XXX            XXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
]

formIconData = [
"24 24 2 1",
"  c navy",
"X c None s None",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXX               XXXXX",
"XXXX               XXXXX",
"XXXX               XXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX             XXXXXXX",
"XXXX             XXXXXXX",
"XXXX             XXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXX     XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
]
